### ISSUE TITLE
Xreal Air + H->C Cable doesn't work

### ISSUE THREAD

**Issue by TIGamingTV** [GingerXR/products#15]
When I start the Virtual desktop I get the text "Starting Headtracking 6sec" after Headtracking started my screen goes black. When I move my head, the screen moves with me. I can control the courser but nothing happens when I click left or right click.

**Comment by GingerXR** [comment]
Hi, I am not sure what H->C means. but in general HDMI does not allow head tracking since there is no way for the sensor data to be transmitted.

Could you please send in a support request through the app itself and make sure enable include log option so that we can take a look.

**Comment by TIGamingTV** [comment]
With h->C Cable I meant and hdmi(+usb) to usb-c cable. Headtracking should work with this, since creak nebula and open track. When I`m later at home I will send the log over the app
