### ISSUE TITLE
gignerxr + xreal air 2 pro

### ISSUE THREAD

**Issue by toppyishappy** [GingerXR/products#18]
my glass only mirror the laptop screen. I want to make an ar screen.

**Comment by toppyishappy** [comment]
I can't create virtual desktop on my glass..
![image](https://github.com/GingerXR/products/assets/40524345/b47cb036-3b97-42c8-a92b-a6d5777f4f71)

**Comment by Lucien-X** [comment]
Same issue here , reproduced in xreal air 2 pro...
I guess the software doesn't recognize the USB Pid and Vid, so I would provide it for you.
The vid is 0x3318 and the pid is 0x0432
Hopefully it will be some help to the developers.

**Comment by Lucien-X** [comment]
Any further update on this???

**Comment by dannietjoh** [comment]
+1. With the severely lacking windows support from xreal gingerxr is a must-have

**Comment by GingerXR** [comment]
Hi guys, sorry for the delay in response, we don't check GitHub as often and this one fell through the cracks.

Unfortunately, Xreal doesn't play nice and rather work on their own solution instead of providing a Windows SDK. so at the moment, we do not support Air 2s.
